site_name: Fashion Intel Docs
theme:
  name: "material"
  palette:
    primary: "blue"
    accent: "blue"

docs_dir: templates
repo_url: https://github.com/oke-aditya/fashion_intel
markdown_extensions:
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
extra_javascript:
  - https://unpkg.com/mermaid@8.4.4/dist/mermaid.min.js

nav:
  - Home: index.md
  - Fashion2Vec: fashion2vec.md
  - Fashion Ranking: ranking.md
  - Fashion Tagging: tagging.md
  - Fashion Search Engine: visualsearch.md